### ISSUE TITLE
A Timeout feature

### ISSUE THREAD

**Issue by dbonates** [gunterhager/UDPBroadcastConnection#2]
Nice UDP Implementation, simple and enough and I'm using it in a new app. A feature that could be convenient would be a timeout after sending broadcasting. In my app I send data, but if my target device is off, no response, then the app just does nothing. Of course I will implement a timeout feature on the app and considering it on the main lib, maybe ;)

**Comment by gunterhager** [comment]
Interesting idea. I see a problem, though: UDP doesn't guarantee responses for every send. I use the broadcast to discover devices on Wifi. Typically you need to send a couple of broadcasts before you decide that no device was found (because very often devices won't answer after the first broadcast).

To me it seems that it would be better to make the app responsible for the retry/timeout logic rather than the low level broadcast library, especially since it'll probably depend on the use-case how many retries you want before you fail (or in my use-case ping forever without failing).

**Comment by dbonates** [comment]
that make sense, 100% agree that the app should take this responsibility  ;)
