### ISSUE TITLE
Outgoing socket port 

### ISSUE THREAD

**Issue by JLightMedia** [gunterhager/UDPBroadcastConnection#6]
Can you tell, how to setup particular outgoing port socket? Every time app create random outgoing port, but I need to use my own.

**Comment by gunterhager** [comment]
I don't think i understand your question. The port is fixed and given by the parameter of the initialiser. I don't see where a random port could come from.

If you mean how to use a given socket (not creating a socket each time we broadcast) - that would mean a major rewrite of the framework. I'm sorry, but i'm currently too busy to implement support for user-provided sockets. Actually, that wouldn't use much functionality of the framework anyway, so maybe it would be better to just implement the broadcast in your app rather than using this framework.

**Comment by JLightMedia** [comment]
Thank you for an answer!
